// foods.ts

export const foods = [
  // === Vegetables ===
  {
    id: 1,
    name: "Cucumber",
    localName: "Огурец",
    category: "vegetable",
    unit: "per100g",
    calories: 15,
    protein: 0.8,
    fat: 0.1,
    carbs: 3.0,
  },
  {
    id: 2,
    name: "Tomato",
    localName: "Помидор",
    category: "vegetable",
    unit: "per100g",
    calories: 18,
    protein: 0.9,
    fat: 0.2,
    carbs: 3.9,
  },
  {
    id: 3,
    name: "Bell Pepper",
    localName: "Сладкий перец",
    category: "vegetable",
    unit: "per100g",
    calories: 27,
    protein: 1,
    fat: 0.2,
    carbs: 6,
  },
  {
    id: 4,
    name: "Brussels Sprouts",
    localName: "Брюссельская капуста",
    category: "vegetable",
    unit: "per100g",
    calories: 43,
    protein: 3.4,
    fat: 0.5,
    carbs: 9,
  },
  {
    id: 5,
    name: "Boiled Beetroot",
    localName: "Свекла вареная",
    category: "vegetable",
    unit: "per100g",
    calories: 49,
    protein: 1.8,
    fat: 0.1,
    carbs: 10,
  },
  {
    id: 6,
    name: "Cauliflower",
    localName: "Цветная капуста",
    category: "vegetable",
    unit: "per100g",
    calories: 30,
    protein: 2.4,
    fat: 0.3,
    carbs: 5,
  },

  // === Dairy ===
  {
    id: 7,
    name: "Greek Yogurt 2%",
    localName: "Греческий йогурт 2%",
    category: "dairy",
    unit: "per100g",
    calories: 59,
    protein: 10,
    fat: 2,
    carbs: 3.6,
  },
  {
    id: 8,
    name: "Matsoni",
    localName: "Мацони",
    category: "dairy",
    unit: "per100g",
    calories: 61,
    protein: 3.5,
    fat: 3.2,
    carbs: 4.2,
  },
  {
    id: 9,
    name: "Cottage Cheese 0%",
    localName: "Творог 0%",
    category: "dairy",
    unit: "per100g",
    calories: 80,
    protein: 18,
    fat: 0.5,
    carbs: 3.3,
  },
  {
    id: 10,
    name: "Suluguni Cheese",
    localName: "Сулугуни",
    category: "dairy",
    unit: "per100g",
    calories: 285,
    protein: 20,
    fat: 22,
    carbs: 2,
  },

  // === Meat & Fish ===
  {
    id: 11,
    name: "Boiled Chicken Breast",
    localName: "Куриная грудка варёная",
    category: "meat",
    unit: "per100g",
    calories: 165,
    protein: 31,
    fat: 3.6,
    carbs: 0,
  },
  {
    id: 12,
    name: "Boiled Turkey",
    localName: "Индейка отварная",
    category: "meat",
    unit: "per100g",
    calories: 135,
    protein: 29,
    fat: 1,
    carbs: 0,
  },
  {
    id: 13,
    name: "Lean Boiled Beef",
    localName: "Говядина постная варёная",
    category: "meat",
    unit: "per100g",
    calories: 190,
    protein: 27,
    fat: 8,
    carbs: 0,
  },
  {
    id: 14,
    name: "Baked Seabass",
    localName: "Сибас запечённый",
    category: "fish",
    unit: "per100g",
    calories: 120,
    protein: 20,
    fat: 4,
    carbs: 0,
  },
  {
    id: 15,
    name: "Chicken Kebab",
    localName: "Куриный кебаб",
    category: "meat",
    unit: "per100g",
    calories: 150,
    protein: 18,
    fat: 7,
    carbs: 2,
  },

  // === Grains ===
  {
    id: 16,
    name: "Buckwheat (dry)",
    localName: "Гречка сухая",
    category: "grain",
    unit: "per100g",
    calories: 340,
    protein: 13,
    fat: 3.4,
    carbs: 72,
  },
  {
    id: 17,
    name: "Cooked Rice",
    localName: "Рис варёный",
    category: "grain",
    unit: "per100g",
    calories: 130,
    protein: 2.4,
    fat: 0.2,
    carbs: 28,
  },
  {
    id: 18,
    name: "Rolled Oats",
    localName: "Овсянка долгой варки",
    category: "grain",
    unit: "per100g",
    calories: 370,
    protein: 12,
    fat: 7,
    carbs: 64,
  },

  // === Fruits ===
  {
    id: 19,
    name: "Kiwi",
    localName: "Киви",
    category: "fruit",
    unit: "per100g",
    calories: 61,
    protein: 1.1,
    fat: 0.5,
    carbs: 14,
  },
  {
    id: 20,
    name: "Pomegranate",
    localName: "Гранат",
    category: "fruit",
    unit: "per100g",
    calories: 72,
    protein: 0.7,
    fat: 0.6,
    carbs: 16,
  },
  {
    id: 21,
    name: "Dried Persimmon",
    localName: "Сушёная хурма",
    category: "fruit",
    unit: "per100g",
    calories: 274,
    protein: 1.4,
    fat: 0.6,
    carbs: 73,
  },
  {
    id: 22,
    name: "Dried Peach",
    localName: "Сушёный персик",
    category: "fruit",
    unit: "per100g",
    calories: 239,
    protein: 3.6,
    fat: 0.8,
    carbs: 57,
  },

  // === Nuts ===
  {
    id: 23,
    name: "Almonds",
    localName: "Миндаль",
    category: "nuts",
    unit: "per100g",
    calories: 579,
    protein: 21,
    fat: 50,
    carbs: 22,
  },
  {
    id: 24,
    name: "Cashews",
    localName: "Кешью",
    category: "nuts",
    unit: "per100g",
    calories: 553,
    protein: 18,
    fat: 44,
    carbs: 33,
  },

  // === Other ===
  {
    id: 25,
    name: "Ayran",
    localName: "Айран",
    category: "other",
    unit: "per100g",
    calories: 27,
    protein: 2.2,
    fat: 1,
    carbs: 2.6,
  },
  {
    id: 26,
    name: "Boiled Egg",
    localName: "Яйцо варёное",
    category: "other",
    unit: "per100g",
    calories: 155,
    protein: 13,
    fat: 11,
    carbs: 1.1,
  },
];

